// src/psi_agent/gateway/spa-v2/src/components/PathPickerDialog.tsx
import { ArrowUp, Folder, HardDrive, Loader2, Search, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import {
  browseWorkspace,
  fetchWorkspacePlaces,
  type BrowseEntry,
  type WorkspaceDrive,
  type WorkspacePlace,
} from '../services/api'
import './path-picker.css'

function normalizePath(path: string): string {
  return path.replace(/\\/g, '/').replace(/\/+$/, '')
}

function filterEntries(entries: BrowseEntry[], query: string): BrowseEntry[] {
  const q = query.trim().toLowerCase()
  const list = [...entries].sort((a, b) => {
    const ak = a.kind === 'directory' ? 0 : 1
    const bk = b.kind === 'directory' ? 0 : 1
    if (ak !== bk) return ak - bk
    return a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })
  })
  if (!q) return list
  return list.filter((e) => e.name.toLowerCase().includes(q))
}

type Props = {
  open: boolean
  initialPath?: string
  title?: string
  confirmLabel?: string
  hint?: string
  onConfirm: (path: string) => void
  onCancel: () => void
}

/** Directory picker backed by Gateway `/workspace/places` + `/workspace/browse` (spa v1 parity). */
export default function PathPickerDialog({
  open,
  initialPath = '',
  title = '选择文件夹',
  confirmLabel = '选择文件夹',
  hint = '',
  onConfirm,
  onCancel,
}: Props) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [places, setPlaces] = useState<WorkspacePlace[]>([])
  const [drives, setDrives] = useState<WorkspaceDrive[]>([])
  const [currentPath, setCurrentPath] = useState('')
  const [selectedPath, setSelectedPath] = useState('')
  const [parent, setParent] = useState('')
  const [segments, setSegments] = useState<{ name: string; path: string }[]>([])
  const [entries, setEntries] = useState<BrowseEntry[]>([])
  const [filterText, setFilterText] = useState('')
  const [address, setAddress] = useState('')

  const visible = useMemo(() => filterEntries(entries, filterText), [entries, filterText])
  const canGoUp = Boolean(parent && normalizePath(parent) !== normalizePath(currentPath))

  const loadBrowse = async (path: string) => {
    setLoading(true)
    setError('')
    try {
      const data = await browseWorkspace(path, { kind: 'directory' })
      const next = data.path || path
      setCurrentPath(next)
      setSelectedPath(next)
      setAddress(next)
      setParent(data.parent || '')
      setSegments(Array.isArray(data.segments) ? data.segments : [])
      setEntries(Array.isArray(data.entries) ? data.entries : [])
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (!open) return
    let cancelled = false
    ;(async () => {
      setLoading(true)
      setError('')
      setFilterText('')
      try {
        const placesData = await fetchWorkspacePlaces()
        if (cancelled) return
        setPlaces(Array.isArray(placesData.places) ? placesData.places : [])
        setDrives(Array.isArray(placesData.drives) ? placesData.drives : [])
        const data = await browseWorkspace(normalizePath(initialPath) || '', { kind: 'directory' })
        if (cancelled) return
        const next = data.path || normalizePath(initialPath)
        setCurrentPath(next)
        setSelectedPath(next)
        setAddress(next)
        setParent(data.parent || '')
        setSegments(Array.isArray(data.segments) ? data.segments : [])
        setEntries(Array.isArray(data.entries) ? data.entries : [])
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e))
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [open, initialPath])

  useEffect(() => {
    if (!open) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onCancel()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open, onCancel])

  if (!open) return null

  return (
    <div className="path-picker-overlay" role="presentation" onClick={onCancel}>
      <div
        className="path-picker-dialog"
        role="dialog"
        aria-modal="true"
        aria-label={title}
        onClick={(e) => e.stopPropagation()}
      >
        <header className="path-picker-header">
          <h3>{title}</h3>
          <button type="button" className="path-picker-icon-btn" aria-label="关闭" onClick={onCancel}>
            <X size={18} />
          </button>
        </header>
        {hint ? <p className="path-picker-hint">{hint}</p> : null}

        <div className="path-picker-body">
          <aside className="path-picker-nav">
            {drives.length > 0 && (
              <div className="path-picker-nav-section">
                <div className="path-picker-nav-label">此电脑</div>
                {drives.map((d) => (
                  <button key={d.path} type="button" className="path-picker-nav-item" onClick={() => void loadBrowse(d.path)}>
                    <HardDrive size={16} />
                    <span>{d.label}</span>
                  </button>
                ))}
              </div>
            )}
            <div className="path-picker-nav-section">
              <div className="path-picker-nav-label">快捷位置</div>
              {places.map((p) => (
                <button key={p.id} type="button" className="path-picker-nav-item" onClick={() => void loadBrowse(p.path)}>
                  <Folder size={16} />
                  <span>{p.label}</span>
                </button>
              ))}
            </div>
          </aside>

          <section className="path-picker-main">
            <div className="path-picker-toolbar">
              <button
                type="button"
                className="path-picker-icon-btn"
                title="上级目录"
                disabled={!canGoUp || loading}
                onClick={() => void loadBrowse(parent)}
              >
                <ArrowUp size={16} />
              </button>
              <div className="path-picker-crumbs">
                {segments.map((seg, i) => (
                  <span key={seg.path} className="path-picker-crumb-wrap">
                    <button type="button" className="path-picker-crumb" onClick={() => void loadBrowse(seg.path)}>
                      {seg.name}
                    </button>
                    {i < segments.length - 1 ? <span className="path-picker-crumb-sep">›</span> : null}
                  </span>
                ))}
              </div>
            </div>

            <input
              className="path-picker-address"
              value={address}
              aria-label="路径"
              onChange={(e) => setAddress(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault()
                  void loadBrowse(address.trim())
                }
              }}
            />

            <div className="path-picker-filter">
              <Search size={15} />
              <input
                type="search"
                value={filterText}
                placeholder="筛选当前文件夹"
                aria-label="筛选"
                onChange={(e) => setFilterText(e.target.value)}
              />
            </div>

            {error ? <div className="path-picker-error">{error}</div> : null}
            {loading ? (
              <div className="path-picker-loading"><Loader2 className="spin" size={18} /> 加载中…</div>
            ) : (
              <div className="path-picker-listing" role="listbox">
                {visible.map((entry) => {
                  const disabled = entry.kind !== 'directory'
                  return (
                    <button
                      key={entry.path}
                      type="button"
                      role="option"
                      aria-selected={entry.path === selectedPath}
                      className={`path-picker-entry${entry.path === selectedPath ? ' selected' : ''}${disabled ? ' disabled' : ''}`}
                      disabled={disabled}
                      onClick={() => setSelectedPath(entry.path)}
                      onDoubleClick={() => {
                        if (entry.kind === 'directory') void loadBrowse(entry.path)
                      }}
                    >
                      <Folder size={16} />
                      <span>{entry.name}</span>
                    </button>
                  )
                })}
                {visible.length === 0 ? <div className="path-picker-empty">此文件夹为空</div> : null}
              </div>
            )}
          </section>
        </div>

        <footer className="path-picker-footer">
          <label>
            <span>文件夹</span>
            <input
              value={selectedPath}
              onChange={(e) => setSelectedPath(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && selectedPath.trim()) {
                  e.preventDefault()
                  onConfirm(normalizePath(selectedPath.trim()))
                }
              }}
            />
          </label>
          <div className="path-picker-footer-actions">
            <button type="button" className="path-picker-cancel" onClick={onCancel}>取消</button>
            <button
              type="button"
              className="path-picker-ok"
              disabled={!selectedPath.trim()}
              onClick={() => onConfirm(normalizePath(selectedPath.trim()))}
            >
              {confirmLabel}
            </button>
          </div>
        </footer>
      </div>
    </div>
  )
}

// src/psi_agent/gateway/spa/src/components/PathPickerDialog.vue
<template>
  <div v-if="picker.visible" class="picker-overlay" @click.self="cancelPathPicker">
    <div class="picker-dialog" role="dialog" aria-modal="true" :aria-label="picker.title">
      <header class="picker-header">
        <h3>{{ picker.title }}</h3>
        <button class="icon-btn" type="button" title="关闭" @click="cancelPathPicker">
          <span class="material-symbols-outlined">close</span>
        </button>
      </header>
      <p v-if="picker.hint" class="picker-hint">{{ picker.hint }}</p>

      <div class="picker-body">
        <aside class="picker-nav">
          <div v-if="picker.drives.length" class="nav-section">
            <div class="nav-label">此电脑</div>
            <button
              v-for="d in picker.drives"
              :key="d.path"
              class="nav-item"
              type="button"
              @click="navigatePathPicker(d.path)"
            >
              <span class="material-symbols-outlined">hard_drive</span>
              <span>{{ d.label }}</span>
            </button>
          </div>
          <div class="nav-section">
            <div class="nav-label">快捷位置</div>
            <button
              v-for="r in picker.roots"
              :key="r.id"
              class="nav-item"
              type="button"
              @click="navigatePathPicker(r.path)"
            >
              <span class="material-symbols-outlined">{{ rootIcon(r.id) }}</span>
              <span>{{ r.label }}</span>
            </button>
          </div>
        </aside>

        <section class="picker-main">
          <div class="toolbar">
            <button
              class="icon-btn"
              type="button"
              title="上级目录"
              :disabled="!canGoUp"
              @click="goParentPathPicker"
            >
              <span class="material-symbols-outlined">arrow_upward</span>
            </button>
            <div class="breadcrumbs">
              <template v-for="(seg, i) in picker.segments" :key="seg.path">
                <button
                  class="crumb"
                  type="button"
                  @click="navigatePathPicker(seg.path)"
                >
                  {{ seg.name }}
                </button>
                <span v-if="i < picker.segments.length - 1" class="crumb-sep">›</span>
              </template>
            </div>
          </div>
          <input
            v-model="picker.currentPath"
            class="address-input"
            type="text"
            aria-label="路径"
            @keydown.enter.prevent="submitAddress"
          >

          <div class="filter-row">
            <span class="material-symbols-outlined">search</span>
            <input
              v-model="picker.filterText"
              type="search"
              placeholder="筛选当前文件夹"
              aria-label="筛选"
            >
          </div>

          <div v-if="picker.error" class="picker-error">{{ picker.error }}</div>
          <div v-else-if="picker.loading" class="picker-loading">加载中…</div>
          <div v-else class="listing" role="listbox">
            <div
              v-for="entry in entries"
              :key="entry.path"
              class="listing-item"
              :class="{
                selected: entry.path === picker.selectedPath,
                disabled: entry.kind !== 'directory' && picker.mode === 'directory',
              }"
              role="option"
              @click="onEntryClick(entry)"
              @dblclick="onEntryDblClick(entry)"
            >
              <span class="material-symbols-outlined entry-icon">
                {{ entry.kind === 'directory' ? 'folder' : 'description' }}
              </span>
              <span class="entry-name">{{ entry.name }}</span>
            </div>
            <div v-if="entries.length === 0" class="listing-empty">此文件夹为空</div>
          </div>
        </section>
      </div>

      <footer class="picker-footer">
        <label class="footer-label">文件夹:</label>
        <input
          v-model="picker.selectedPath"
          class="footer-path"
          type="text"
          aria-label="选中的文件夹路径"
          @keydown.enter.prevent="confirmPathPicker"
        >
        <div class="footer-actions">
          <button class="cancel" type="button" @click="cancelPathPicker">取消</button>
          <button class="ok" type="button" :disabled="!picker.selectedPath.trim()" @click="confirmPathPicker">
            {{ picker.confirmLabel }}
          </button>
        </div>
      </footer>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useEventListener } from '@vueuse/core'
import {
  cancelPathPicker,
  confirmPathPicker,
  enterPathPickerEntry,
  goParentPathPicker,
  navigatePathPicker,
  selectPathPickerEntry,
  usePathPickerState,
  visibleEntries,
} from '../composables/usePathPicker.js'
import { normalizeWorkspacePath } from '../sessionList.js'

const picker = usePathPickerState()

const entries = computed(() => visibleEntries())

const canGoUp = computed(() => {
  const parent = normalizeWorkspacePath(picker.parent)
  const current = normalizeWorkspacePath(picker.currentPath)
  return !!parent && parent !== current
})

function rootIcon(id) {
  if (id === 'cwd') return 'terminal'
  if (id === 'home') return 'home'
  if (id === 'desktop') return 'desktop_windows'
  if (id === 'documents') return 'description'
  if (id === 'downloads') return 'download'
  return 'folder'
}

function submitAddress() {
  const path = normalizeWorkspacePath(picker.currentPath)
  if (path) navigatePathPicker(path)
}

function onEntryClick(entry) {
  if (entry.kind === 'directory') {
    selectPathPickerEntry(entry)
    return
  }
  if (picker.mode !== 'directory') selectPathPickerEntry(entry)
}

function onEntryDblClick(entry) {
  if (entry.kind === 'directory') enterPathPickerEntry(entry)
}

useEventListener(window, 'keydown', (e) => {
  if (!picker.visible) return
  if (e.key === 'Escape') {
    e.preventDefault()
    cancelPathPicker()
  }
})
</script>

<style scoped>
.picker-overlay {
  position: fixed;
  inset: 0;
  z-index: 110;
  background: rgba(0, 0, 0, 0.45);
  backdrop-filter: blur(2px);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px;
}
.picker-dialog {
  width: min(760px, 96vw);
  height: min(560px, 88vh);
  background: var(--md-surface-container-high);
  border: 1px solid var(--md-outline-variant);
  border-radius: 20px;
  display: flex;
  flex-direction: column;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);
  overflow: hidden;
}
.picker-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px 8px;
}
.picker-header h3 {
  margin: 0;
  font-size: 20px;
  font-weight: 500;
  color: var(--md-text-primary);
}
.picker-hint {
  margin: 0 20px 8px;
  font-size: 13px;
  color: var(--md-text-secondary);
  line-height: 1.5;
}
.picker-body {
  flex: 1;
  min-height: 0;
  display: flex;
  border-top: 1px solid var(--md-outline-variant);
  border-bottom: 1px solid var(--md-outline-variant);
}
.picker-nav {
  width: 168px;
  flex-shrink: 0;
  overflow-y: auto;
  padding: 8px;
  border-right: 1px solid var(--md-outline-variant);
  background: var(--md-surface-container);
}
.nav-section { margin-bottom: 12px; }
.nav-label {
  font-size: 11px;
  color: var(--md-text-secondary);
  padding: 4px 8px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}
.nav-item {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px;
  border: none;
  border-radius: var(--md-shape-small);
  background: transparent;
  color: var(--md-text-primary);
  font-size: 13px;
  cursor: pointer;
  text-align: left;
}
.nav-item:hover { background: var(--md-nav-hover); }
.nav-item .material-symbols-outlined { font-size: 18px; color: var(--md-primary); flex-shrink: 0; }
.picker-main {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  padding: 8px 12px;
}
.toolbar {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 6px;
}
.breadcrumbs {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 2px;
  min-width: 0;
  flex: 1;
}
.crumb {
  border: none;
  background: transparent;
  color: var(--md-primary);
  font-size: 12px;
  cursor: pointer;
  padding: 2px 4px;
  border-radius: 4px;
  max-width: 120px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.crumb:hover { background: var(--md-nav-hover); }
.crumb-sep { color: var(--md-text-secondary); font-size: 12px; }
.address-input {
  width: 100%;
  margin-bottom: 6px;
  padding: 6px 10px;
  border: 1px solid var(--md-outline);
  border-radius: var(--md-shape-small);
  background: var(--md-surface-variant);
  color: var(--md-text-primary);
  font-size: 12px;
  outline: none;
}
.address-input:focus { border-color: var(--md-primary); }
.filter-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 8px;
  margin-bottom: 6px;
  border-radius: var(--md-shape-full);
  background: var(--md-surface-variant);
}
.filter-row .material-symbols-outlined { font-size: 18px; color: var(--md-text-secondary); }
.filter-row input {
  flex: 1;
  border: none;
  background: transparent;
  color: var(--md-text-primary);
  font-size: 13px;
  outline: none;
}
.listing {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  border: 1px solid var(--md-outline-variant);
  border-radius: var(--md-shape-small);
  background: var(--md-bg);
}
.listing-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 13px;
  border-bottom: 1px solid var(--md-outline-variant);
}
.listing-item:last-child { border-bottom: none; }
.listing-item:hover { background: var(--md-nav-hover); }
.listing-item.selected {
  background: var(--md-nav-hover);
  outline: 1px solid var(--md-primary);
  outline-offset: -1px;
}
.listing-item.disabled { opacity: 0.45; cursor: default; }
.entry-icon { font-size: 20px; color: var(--md-primary); flex-shrink: 0; }
.entry-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.listing-empty,
.picker-loading,
.picker-error {
  padding: 24px;
  text-align: center;
  font-size: 13px;
  color: var(--md-text-secondary);
}
.picker-error { color: var(--md-text-error); }
.picker-footer {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  flex-wrap: wrap;
}
.footer-label {
  font-size: 13px;
  color: var(--md-text-secondary);
  flex-shrink: 0;
}
.footer-path {
  flex: 1;
  min-width: 160px;
  padding: 8px 12px;
  border: 1px solid var(--md-outline);
  border-radius: var(--md-shape-small);
  background: var(--md-surface-variant);
  color: var(--md-text-primary);
  font-size: 13px;
  outline: none;
}
.footer-path:focus { border-color: var(--md-primary); }
.footer-actions {
  display: flex;
  gap: 8px;
  margin-left: auto;
}
.footer-actions button {
  padding: 10px 20px;
  border-radius: var(--md-shape-full);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  border: none;
}
.footer-actions .ok {
  background: var(--md-primary);
  color: var(--md-on-primary);
}
.footer-actions .ok:disabled { opacity: 0.45; cursor: not-allowed; }
.footer-actions .cancel {
  background: transparent;
  color: var(--md-primary);
  border: 1px solid var(--md-outline);
}
.icon-btn {
  width: 32px;
  height: 32px;
  border: none;
  border-radius: 50%;
  background: transparent;
  color: var(--md-text-secondary);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  flex-shrink: 0;
}
.icon-btn:hover:not(:disabled) { background: var(--md-nav-hover); color: var(--md-primary); }
.icon-btn:disabled { opacity: 0.35; cursor: not-allowed; }

@media (max-width: 640px) {
  .picker-nav { display: none; }
  .picker-dialog { height: min(620px, 92vh); }
}
</style>
